### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by Anisha7** [tempor1s/spaceman#1]
Seems like not all guessed letters are detected! When I tested your program, for the word 'cascaded', when I guessed 'a', it counted as an incorrect guess. Testing again with other secret words, they aren't placed in the right location. Come to office hours if you need help debugging this! Tip: Adding print statements at multiple locations in your code will help find the error.

**Comment by tempor1s** [comment]
I think this may be due to sinister spaceman changing the word whenever you have a correct guess?
