### ISSUE TITLE
Feedback on unit tests

### ISSUE THREAD

**Issue by Anisha7** [tempor1s/spaceman#2]
Great job on implementing unit tests! Here's some feedback to improve your code:

- Your test_spaceman.py never runs the tests! They are only defined. Run these functions inside of `if __name__ == '__main__':` so when `python3 test_spaceman.py` is run, you can see the tests run!
- Here’s a common syntax of running code in test files if you are not using unittest module:
	`if __name__==“—main__”:`
	`---print(“Testing function_name…”)`
	`---test_function()`
	`---print(“PASSED”)`
- Alternatively, you can challenge yourself by using the unittest module!

**Comment by tempor1s** [comment]
I am using pytest for tests, so they are run in the console using ‘pytest’, so I don’t need to use unit test or run them in a if __name__ = __main__ func
